vich_uploader:
    db_driver: orm

    mappings:
        dub_images:
            uri_prefix: /images/dub
            upload_destination: '%kernel.project_dir%/public/images/dub'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
